language: bash
services: docker
before_install:  
  - echo "We are in the Docker folder!"
script:
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider: script
  script:
    docker push devthiagofurtado/mysql-full-stack-challenge;
    docker push devthiagofurtado/full-stack-challenge;
    devthiagofurtado/redis-full-stack-challenge;
  on:
    branch: main
notifications:
  email: false