version: '3.4'
services:
  db:
    image: devthiagofurtado/mysql-full-stack-challenge
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: dictionary
    ports:
      - "3308:3306"
    networks:
      - udemy-network
  cache:    
    image: redis
    restart: always
    command: redis-server 
    ports:
      - "6379:6379"    
    networks:
      - udemy-network    
  full-stack-challenge:
    image: devthiagofurtado/full-stack-challenge
    restart: always
    build: ./FullStackChallenge
    working_dir: /FullStackChallenge
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./FullStackChallenge:/FullStackChallenge
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
      - cache
    depends_on:
      - db
      - cache
    networks:
      - udemy-network
networks:
  udemy-network:
    driver: bridge